apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wayback-worker
  labels:
    app: wayback-worker
    track: stable
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wayback-worker
        track: stable
    spec:
      containers:
        - name: wayback-worker
          imagePullPolicy: Always
          image: rosskukulinski/wayback-worker:latest
          env:
          - name: GCLOUD_PROJECT
            valueFrom:
              secretKeyRef:
                name: gcloud-bucket
                key: gcloud-project
          - name: GCLOUD_KEYFILE
            value: /var/gcloud/gcloud.json
          volumeMounts:
          - mountPath: /var/gcloud
            name: gcloud-bucket
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 2
            timeoutSeconds: 5
      volumes:
      - name: gcloud-bucket
        secret:
          secretName: gcloud-bucket
